CREATE TABLE IF NOT EXISTS school_year (
    school_year_id INT(10) NOT NULL PRIMARY KEY,
    school_year INT(50) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    
);