CREATE TABLE IF NOT EXISTS section (
    section_id INT(10) NOT NULL PRIMARY KEY,
    section_name VARVARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    
);